# Generated by Django 3.0.5 on 2020-07-22 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('phno', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=300)),
                ('items', models.CharField(max_length=500)),
                ('rest_name', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrentOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('phno', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=300)),
                ('items', models.CharField(max_length=500)),
                ('rest_name', models.CharField(max_length=100)),
                ('total_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('item_id', models.IntegerField()),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('qty', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Items')),
            ],
        ),
    ]
