# Generated by Django 3.0.5 on 2020-07-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='qauntity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
