# Generated by Django 3.0.5 on 2020-07-22 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_cart_qauntity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
